Automattic/Edit-Flow

.travis.yml
bin/install-wp-tests.sh
tests/bootstrap.php

Fixes broken testing in Travis-CI. Updated by running the WP-CLI
scaffolding command.
https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests

Update testing framework

---

modules/notifications/notifications.php

send the correct post time in notifications

---

edit_flow.php

0.8.1 has been released, bumping to 0.8.2-alpha.

Bump EDIT_FLOW_VERSION

---

common/php/class-module.php
tests/test-class-module.php

Doing some minor cleanup on @jeremyclarke's PR #328 per @mjangda's comments.
@jeremyclarke @mjangda do you have a minute to review?

Fix $post_int init

---

README.md

Add bugfix, localization and improvements to Readme. Shoutouts to respective contributors.

Add to Readme for v0.8.2

---

tools/deploy-to-svn.sh

Adding a script to help with SVN deployments based off of the that [exists in Jetpack](https://github.com/Automattic/jetpack/blob/master/tools/deploy-to-svn.sh).

Add SVN deloyment script

---

README.md
readme.txt

Few more readme updates

---

common/php/screen-options.php

Remove PHP4 constructor from Screen Options class

---

languages/edit-flow-pt_BR.po

Adequei alguns aspectos da tradução para a linguagem correta das redações de jornais e de blogs.

Texto corrigido e traduções acrescentadas

---

README.md
readme.txt

Updating props on README for 0.8.2

---

README.md
edit_flow.php
readme.txt

Version bumping prior to release

Bumping up version fo 0.8.2

---

modules/calendar/calendar.php
modules/story-budget/story-budget.php

As suggested to me- separate pull request from Russian translation update.

i18n dates for calendar and story budget

---

modules/custom-status/custom-status.php
wpcom-helper.php

Adding a new filter to modify the "post name" along with a wpcom-helper.php function

Adding ef_fix_post_name_post

---

common/js/jquery.listfilterizer.js
edit_flow.php

Fixes #314 - translate jquery-listfilterizer

Localize jquery-listfilterizer

---

modules/custom-status/custom-status.php
modules/custom-status/lib/custom-status.js

Change all the text strings in custom-status.js to translatable variables

Localize custom-status.js

---

modules/notifications/notifications.php

1) Fixes : `PHP Notice:  Undefined index: …/plugins/Edit-Flow/modules/notifications/notifications.php on line 370`.
2) Fixes: `PHP Notice:  Undefined index: _nonce in .../plugins/Edit-Flow/modules/notifications/notifications.php on line 365`
2) Adds further checks to make sure all values are set before accessing them.
3) General cleanup and coding standards for the method.
______
To replicate the error and test this patch:
1) Add some user group subscriptions to a post.
2) Remove all groups from the subscriptions.
3) Note the php notice in the logs.

Prevent undefined index error during subscriptions saving

---

modules/calendar/calendar.php

Initial thoughts/proposal for #417

Support adding non-post data into days of calendar #417

---

modules/user-groups/user-groups.php

This was required for one of our projects to allow filtering of user_ids on the object.

Added user_group object filter for better flexibility

---

modules/editorial-comments/editorial-comments.php
modules/editorial-comments/lib/editorial-comments.css
modules/editorial-comments/lib/editorial-comments.js
modules/notifications/lib/notifications.js

Reverts Automattic/Edit-Flow#472

Revert "Revert "Display who was notified for an editorial comment""

---

modules/calendar/calendar.php

A hook has been added to insert post thumbnail. 
Example

Added  hook `ef_calendar_item_html` to Calendar

---

.gitignore

Remove `edit-flow.php` from gitignore

---

modules/user-groups/user-groups.php

Bring in the changes from #490
While testing this, I encountered compatibility issues between Ninja Shop and the Custom Types module in Edit Flow. Logging that as a separate issue

Wrap network check with block to ensure function exists

---

README.md
edit_flow.php
readme.txt

Adds changelog and version bumps to prepare for v0.9.1.

Readme and version bump for 0.9.1

---

.svnignore
PUBLISHING.md
bin/prepare-svn-release.sh

Misc improvements to the docs and release script after pushing a release.

Update publishing instructions

---

tests/test-edit-flow-custom-status.php

The custom status automated tests are failing on the latest version of WP. Just making a small fix

Update custom status tests

---

README.md
edit_flow.php
readme.txt

Preparing for release. Includes readme updates and version bumps.

Prepare 0.9.3

---

README.md
edit_flow.php
readme.txt

Preparing for release. Includes readme updates and version bumps.

Prepare 0.9.4

---

README.md
edit_flow.php
readme.txt

Updating in prepartion for 0.9.5

Prepare 0.9.5

---

modules/calendar/calendar.php

Fixing up all the existing PHPCS errors for `calendar.php`.

Fixing up PHPCS errors for calendar

---

modules/calendar/lib/calendar.css

Some minor tweaking of the calendar styling to tide us over until we start on a more comprehensive update of the calendar.

Tiny style tweaks to calendar

---

modules/calendar/lib/calendar.css

Small style update to make calendar item background white (so they don't look disabled on weekend days)

Update calendar item background-color to white

---

edit_flow.php

:wave: Just a quick reminder that this is a public repo. Please don't include any internal links or sensitive data (like PII, private code, client names, site URLs, etc. If you're not sure if something is safe to share, please just ask!
If you're not an Automattician, welcome! We look forward to your contribution! :heart:
Please remove this section before submitting the PR.
---
A few sentences describing the overall goals of the Pull Request.
Should include any special considerations, decisions, and links to relevant GitHub issues.
Please don't include internal or private links :)
Outline the steps to test and verify the PR here.
Example:
1. Check out PR.
1. Go to Calendar.
1. Add a pitch titled "why cookies are so delicious".
1. Verify post is also delicious.

Bump version to 0.9.8
