modules/notifications/lib/notifications.js

Fix for current version of jQuery and the "All posts" page. Would
previously hang on page load with current versions of WordPress.

Javascript performance

---

modules/custom-status/custom-status.php
modules/editorial-comments/editorial-comments.php

WordPress 4.5 deprecates `get_currentuserinfo` for `wp_get_current_user`. And a little whitespace cleanup.

Remove depreciated function get_currentuserinfo

---

modules/calendar/calendar.php
modules/story-budget/story-budget.php

The `$post` param was added to `preview_post_link` in 4.0. Without it here it will throw warnings for others that are using the filter and expecting it to be present.

Adding $post param to preview_post_link filter to prevent warning.

---

modules/calendar/calendar.php

If a custom user role has been created for write access to the calendar via the filter on https://github.com/Automattic/Edit-Flow/blob/master/modules/calendar/calendar.php#L87 and that user doesn't have WP `publish_posts` capabilities, they won't be able to create calendar entries. Proposing changing the check from `publish_posts` to `$this->create_post_cap`

Proposed fix on Calendar module for "current_user_can" capability check

---

common/php/class-module.php
modules/custom-status/custom-status.php
tests/test-class-module.php

Encountering the "only variables should be assigned by reference" and "only variables should be passed by reference" warnings when PHP strict standards are enabled. Cleanup instances in the code where these warnings are being triggered.
**fix for #311**
`$role = get_role( $role );`
Don't think we need the `&` if I'm reading http://php.net/manual/en/language.oop5.references.php correctly. Can someone with a bit more PHP expertise verify that?
**fix for #321**
`$default_status = array_shift( $custom_statuses );`
Looks like we need to pass a variable to `array_shift` instead of the return value of `$this->get_custom_statuses() `
**edit:** tagging issue correctly

Cleanup PHP to comply with strict standards

---

modules/dashboard/widgets/dashboard-notepad.php
tests/test-edit-flow-dashboard-notepad.php

This adds the label 'Dashboard Note' when registering the dashboard-note post type. Also adds `WP_Test_Edit_Flow_Dashboard_Note` to test EF_Dashboard_Notepad_Widget. Currently tests that EF_Dashboard_Notepad_Widget properly registers the dashboard-note post type.

Add label to Dashboard Note and tests

---

modules/custom-status/custom-status.php

Previously was just covering 'publish' and 'future'. Should also cover 'private'. Rather than trying to account for these, if the status is not in this array return early.

Modify custom_status_timestamp to cover more statuses.

---

CONTRIBUTING.md

This patch adds a CONTRIBUTING.md file with guidelines and directions for how folks can contribute to Edit Flow. It's largely based off of the contributing guidelines for the Jetpack plugin.

Adding guidelines for contributing

---

modules/custom-status/custom-status.php
tests/test-edit-flow-custom-status.php

`get_sample_permalink_html` checks the status of a post in order to generate the html needed to support editing the permalink. To circumvent this we'll leverage the get_sample_permalink_html filter to rework the html after get_sample_permalink_html has run.

[WIP] Emulate get_sample_permalink_html

---

tests/test-edit-flow-dashboard-notepad.php

Remove `assertInstanceOf` from the test-edit-flow-dashboard-notepad test. `get_post_type_object` now returns a WP_Post_Type object instead of stdClass. The `assertEqual` clause should be fine.

Clean up dashboard notepad unit test

---

modules/notifications/notifications.php

When creating a new page via WP-CLI using `wp post create` and not specifying the author, a PHP notice is occurring.
```
vagrant@vvv:/srv/www/wordpress-default/htdocs/wp-content$ wp post create post-content.html --post_type=page --post_title="New Page"
PHP Notice:  Trying to get property of non-object in /srv/www/wordpress-default/htdocs/wp-content/plugins/edit-flow/modules/notifications/notifications.php on line 567
```
This patch checks for an empty `$post_author` variable before trying to access the properties in the variable.

Added check for empty author in notifications

---

tests/test-edit-flow-custom-status.php

tests. Make sure it's installed correctly. Todo: ensure modules for all
tests are properly initialized.

The custom status module was not being properly initialized when running

---

modules/custom-status/custom-status.php
modules/editorial-metadata/editorial-metadata.php
modules/user-groups/user-groups.php

Fixing typo in reference to $this->module->message array, as reported in #313

fix typo for module messages

---

modules/settings/lib/settings.css

The `configure-edit-flow-module` buttons on the Edit Flow settings
screen had a blue-tint applied to the text and button styling by
WordPress core. Adding two style changes to bring back the previous look
and feel.

Restyle `configure-edit-flow-module` buttons.

---

modules/calendar/calendar.php

Used date_i18n not WP_locale as either the latter behaves strange or I just didn't manage to understand that.
Anyway, with date_i18n both days and months work as they should.

Days of week and months are localized properly now

---

modules/editorial-comments/editorial-comments.php

The `apply_filters` function is getting called wrongly. (ie) The return value of the function is not getting stored anywhere, esentially rendering the filter useless.
This PR fixes that and also passes `$_POST` as an additional parameter to the filter.

Fix ef_pre_insert_editorial_comment filter

---

modules/notifications/notifications.php

Fix for php warning: Warning: array_map(): Argument #2 should be an array in /plugins/edit-flow/modules/notifications/notifications.php on line 370
Request: 
pmcwwd.wordpress.com/wp-admin/admin-ajax.php
Pushed to master at r304610.
Props Michael Auteri.

Fix for warning on array_map()

---

.travis.yml

Since WordPress doesn`t support hhvm anymore, lets decrease the unit testing complexity by removing it here too

travis-ci: drop support for hhvm

---

modules/calendar/calendar.php

The missing part was the text domain for the output and that's all. This time I escaped the output later (based on this https://vip.wordpress.com/documentation/validating-sanitizing-escaping/#always-escape-late) This PR fixes #377

Changed the output of status on the calendar

---

modules/custom-status/custom-status.php
modules/custom-status/lib/custom-status.js

There was still room for improvement in #414
A cleaner solution available in pull requests #419 and #420 
This will revert Automattic/Edit-Flow#414 so that #419 and #420 can be merged in.

Revert "Fix #389 - Custom Statuses in Pages"

---

modules/calendar/calendar.php

Fixes #236 
[It's recommended](https://vip.wordpress.com/documentation/code-review-what-we-look-for/#no-limit-queries) to limit `posts_per_page` when possible. 
I think that 200 posts per week should be a reasonable upper limit for 99.99% use cases. For the remaining 0.01%, a simple filter can easily revert this back:
```
add_filter( 'ef_calendar_posts_query_args', function( $args ) {
$args['posts_per_page'] = -1;
return $args;
});
```

Limit posts_per_page in calendar week query

---

modules/custom-status/custom-status.php

This will ensure that variables are passed to `custom-status.js` even when `global $post` is not available (for example, in Page list). 
`$selected` and `$selected_name` variables are only used in single view, so they can be left empty if there is no `global $post` object available.
Also, a micro-optimization is included that breaks out of the `foreach` loop when the `$selected_name` is found

Fix #389 - pass custom-status variables to JavaScript on all whitelisted pages

---

modules/calendar/calendar.php
modules/story-budget/story-budget.php

Fixes #248 
Possibly a breaking change: Removing method `post_where_week_range` from the `posts_where` filter.

Avoid direct SQL Queries by using WP Date Query

---

modules/calendar/calendar.php

This fixes a problem where incorrect times were added to calendars because calendars expect a times to be in UTC+0 time zone. The problem described in #243 
Introduced `ics_format_time` static method that is formatting the time properly.

Fix #243 - Offset post times to UTC+0 for Calendars

---

modules/calendar/calendar.php

Issue #252 was caused because whole chunks of HTML are cached, including nonces that are specific to the current user. This fix caches the HTML fragments to the current user. 
An alternative to this fix would be to ajaxify the delete button, but that would take more effort to implement. This fixes a bug, I think that's good enough for now.

Fix #252 - Cache calendar fragments for each user

---

tests/bootstrap.php

When the tests folder is installed locally, the folder might be different than the one used on travis. That's why I added a check. If the path to the tests is found in the environment variables, that one is used. If not, a default path is used. I made this change because the tests were installed on a different folder on my computer and I didn't want to change the $_tests_dir (not even for a test) because I might push it to the plugin (by mistake) and I thought about this workaround.

Added a check for the tests dir

---

common/css/edit-flow-admin.css

A tiny fix for when Gutenberg styles break Edit Flow metabox lists.
Fixes #430

Remove gutenberg list styles from Edit Flow metaboxes

---

modules/dashboard/dashboard.php
modules/dashboard/lib/dashboard.css

Add a widget "Unpublished Content" for each post type that Edit Flow supports. This was a very popular request in #63 and people were desperate enough for the feature to try to monkeypatch the plugin. 
This closes #63 and removes a `// @todo` from code

Add "Unpublished Content" widget for each supported post type

---

common/php/util.php
modules/custom-status/custom-status.php

Fix #192 
WordPress doesn't fully support custom post statuses, which is why there are many "hacks" inside Edit Flow. This is another one.
There is no way to tell `_wp_link_page()` function that we have other statuses besides draft that are still unpublished. That's why I copied original `_wp_link_page()` function, renamed it to `_ef_wp_link_page()` and added support for custom post statuses.
Then the `_ef_wp_link_page()` function is used to generate a new link when in preview mode using the `wp_link_pages_link` filter.

Fix broken in-post pagination when custom post statuses are used

---

.travis.yml
bin/install-wp-tests.sh
tests/bootstrap.php
tests/phpunit/multisite.xml

This PR adds standard PHPUnit setup files, as they are generated by the `wp scaffold plugin-tests` command of the [WP CLI project](https://developer.wordpress.org/cli/commands/scaffold/plugin-tests/).
Primarily, this adds the `bin/install-wp-tests.sh` file, which installs the WordPress and test suite to common location. The location is then used in the test/bootstrap.php file.
Further, a multisite.xml config is added to the location which is being mentioned by WordPress PHPUnit test suite for running in MS mode:
```
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
```
Which `multisite.xml` in that location, following command works like a charm for the phpunit command run from within the plugin:
```
phpunit -c tests/phpunit/multisite.xml
```

Add local PHPUnit setup

---

modules/dashboard/widgets/dashboard-notepad.php

Fix #245 
The dashboard notepad was generating an unused WordPress rewrite. This pull removes that behavior.

Don’t generate rewrite rules for notepad

---

common/php/class-module.php
modules/calendar/calendar.php
modules/custom-status/custom-status.php
modules/custom-status/lib/custom-status.css
modules/notifications/notifications.php
modules/story-budget/story-budget.php

Fixes #445
Previously, the `get_post_status_friendly_name` function was retrieving the WordPress built-in Post Statuses and the Custom Statuses set within the plugin interface.  If you happen to register a post status another way, it would not appear in the Status Column of your Post Type.
This PR removes the need for `get_post_status_friendly_name` in the Post List, Calendar, and Story Budget sections and instead just calls the post status label directly.
This also adds a check to see if a Post State does not match the Post Status, and if it does not match, it will show the Post State.  Example:

Fix status list, calendar, and story budget to show custom post statuses and show post states in post list.

---

vipgo-helper.php

In Edit Flow, we check for the `ef_view_story_budget` capability before to display some of the admin pages. The `ef_view_story_budget` capability should be given to admins, editors, and authors here:
- https://github.com/Automattic/Edit-Flow/blob/master/modules/story-budget/story-budget.php#L86-L101
- https://github.com/Automattic/Edit-Flow/blob/master/edit_flow.php#L194-L197
However, this does not get to run on VIP Go sites, thus leaving users without the custom caps necessary to access the different Edit Flow custom screens. To solve this, let's add all necessary caps via filters.
Reported in 76616-zd-wordpressvip

Capabilities: add capabilities via filters on VIP Go sites.

---

modules/calendar/calendar.php
modules/story-budget/story-budget.php

Screen Options panel only exists in Dashboard, and there's no good reason to run on every `init` action.
Fixes #354, supersedes #443.

Move out add_screen_options_panel from init to admin_init for Calendar and Story budget modules

---

modules/story-budget/lib/story-budget.css
modules/story-budget/lib/story-budget.js
modules/story-budget/story-budget.php

Made the changes discussed here: https://github.com/Automattic/Edit-Flow/pull/409#issuecomment-383417463
The old branch was no longer available so I created another PR. The only thing that I made different is that I added `columns-number-` in
```
echo '<div class="postbox-container columns-number-' . $this->num_columns . '">';
foreach( (array) $this->terms as $term ) {
$this->print_term( $term );
}
```
because it wasn't working without this part. Basically, this is the initial number of columns that it's removed by this JS code:
```
$(".postbox-container").removeClass(function() {
for (var index = 1, c = []; index <= columnsSwitch.length; index++) {
c.push( classPrefix + index )
}
return c.join(' ');
})
```
Everything else is just what you suggested.

Story budget - Screen Option columns option fix

---

modules/dashboard/widgets/dashboard-notepad.php

The function `handle_notepad_update()` used to use `$_REQUEST`, which is [against best practices](https://vip.wordpress.com/documentation/code-review-what-we-look-for/#using-_request). 
Before #469, the form did not specify a method so it defaulted to GET. With #469, we changed the method to POST, so all references to `$_REQUEST` have been updated with the corresponding `$_POST` ones.
**NOTE** that this depends on #469, because it expects the HTML form to use the POST method, or the note saving will just not work.

Changed $_REQUEST usage to $_POST usage in handle_notepad_update()

---

modules/calendar/calendar.php

The method get_beginning_of_week has some flaws which I addressed in this commit.
1. The comments make no sense (mixing up end of week and beginning of week)
2. When the passed $date is not a start of the week and the passed number $week is greater than 1, the method will behave incorrectly, because the difference between $day_of_week and $start_of_week is then subtracted multiple times. In the current calendar implementation this seems to have no negative effect, because the passed $date will always be a start of a week. But I thought it would be proper to fix it anyway.
3. When, by means of the given offset of $week, a DST switch introducing additional time occurs during the period between $date and the final date, the method will also behave incorrectly (the same date(s) may occur …

Fix get_beginning_of_week

---

modules/editorial-comments/editorial-comments.php
modules/editorial-comments/lib/editorial-comments.css
modules/editorial-comments/lib/editorial-comments.js
modules/notifications/lib/notifications.js

Part of https://github.com/Automattic/Edit-Flow/issues/270. This PR started in https://github.com/Automattic/Edit-Flow/pull/271, and continued with some edits here.
The functionality is the same as described in 271 above, with a few smaller changes:
- Only save comment meta if needed (don't save empty messages).
- Localize all text strings.
- Add filter so this feature can be disabled.
To test:
1) Enable notifications & editorial comments features.
2) Add people and/or groups to be notified.
3) Leave editorial comments.
Screenshots can be found in https://github.com/Automattic/Edit-Flow/pull/271, as there weren't many changes to the display (aside from colors and text aligning).

Display who was notified for an editorial comment

---

modules/editorial-comments/editorial-comments.php
modules/editorial-comments/lib/editorial-comments.css
modules/editorial-comments/lib/editorial-comments.js
modules/notifications/lib/notifications.js

Revert "Display who was notified for an editorial comment"

---

modules/dashboard/widgets/dashboard-notepad.php

The Notepad Dashboard Widget was showing the note creation time, even if the label said _last updated at_, as reported in #465. The issue was due to the usage of `get_the_time()` instead of `get_the_modified_time()`.

Displaying updated time instead of creation time in Notepad Dashboard Widget

---

modules/settings/lib/settings.css

For #480 
The green color doesn't make a lot of sense, and has had an ugly blue shadow for a long time.
Why not remove the green entirely? It looks good with blue buttons, and won't cause headaches in the future if button-primary changes again.

settings.css - remove green color on module-enabling button-primary buttons

---

modules/settings/lib/settings.css

Fix styling not being optimal on mobile devices (and small resolutions in general), as proposed in #361. 
In particular,
- Enlarged module boxes and button divs from 210px to 250px to prevent buttons from overlapping.
- Removed `min-width` property from modules container, which prevented the page from being fully adaptable to different resolutions.
Any viewer which is at least ~ 250px wide should see the page well. Tested with Chrome (with variable window size) and a mobile emulator. Now, if the viewer is not at least ~ 500px wide, module boxes are all stacked in a single column.
**Before CSS changes**
**After CSS changes**

Enlarged modules box up to 250px, so that buttons don't overlap anymore

---

modules/notifications/notifications.php

Part of https://github.com/Automattic/Edit-Flow/issues/265
The functionality is all implemented in the first commit, the other two are cleanup for it's surroundings.
It's possible that the `user_can_be_notified` method will need to be abstracted and put into the `EF_Module` parent class for part 2 of the above issue, but that can be done if/when necessary.
And then it seems calling both `edit_post` or `edit_page` conditionally would be redundant according to the core method: https://github.com/WordPress/WordPress/blob/master/wp-includes/capabilities.php#L127-L128. Would be nice to have a second pair of eyes to confirm this, but my testing showed that this was indeed the case. Some more info on what I found here https://github.com/Automattic/Edit-Flow/issues/265#issuecomment-378419531
1) …

Check if a user can edit the post/page before sending a notification.

---

common/php/class-module.php
modules/notifications/lib/notifications.css
modules/notifications/lib/notifications.js
modules/notifications/notifications.php

For https://github.com/Automattic/Edit-Flow/issues/451
Recap of what's being done in this PR:
1) Adds a "No Access" badge for users on page load. The permissions checks are only done for users that are already subscribed.
2) When users are selected and saved via ajax, the response sends back a list of checked user IDs that do not have access. Can then use this list to find out if the newly selected user needs the badge or not.
I prototyped a bit ahead, thinking of how #273 could be implemented. So some of the organization here had those changes in mind.
Also note that I added the `user_can_be_notified()` method in for testing purposes, but can remove/leave out when it comes to merging into the feature branch.
Screenshot:

Add a "No Access" badge to subscribers that will not be able to receive notifications

---

modules/notifications/notifications.php

For #478  
- Updates phpdoc to specify that $comment is WP_Comment
- Near the top, we fetch the list of users/groups from comment meta
- Before the "actions" list, we output the list of people who were notified
Note: This template could use so much love, but for now focusing on putting this new feature in a sensible place, with a plan to return and redesign the template later.

Update EF_Notifications->notification_comment() to insert the list of users/groups who were notified

---

modules/editorial-comments/lib/editorial-comments.js

Update jQuery that pulls text from subscribed users
This is a fix for the already-merged #461 already described in a comment there: 
https://github.com/Automattic/Edit-Flow/pull/461#issuecomment-437193887
Currently the "notified list" feature is totally broken. 
WHAT THIS CHANGES
- The jQuery used to get the text from the node next to the textbox (username)
- There is now an extra div around the checkbox (added as part of the NO ACCESS feature), so this is broken.
- New jQuery gets the parent of the checkbox, then searches it's siblings for the displayname and uses that

editorial-comments.js - fix jQuery that updates notified list

---

common/php/class-module.php
modules/editorial-comments/lib/editorial-comments.js
modules/notifications/lib/notifications.css
modules/notifications/lib/notifications.js
modules/notifications/notifications.php

No Access and No Email badges both work using a unified system now, and those users aren't added to the "Notified list". 
The current user's checkbox is marked with a special class, and the "Notification list" JS is set up to ignore the current user. 
For #483 - Updates notifications js/php to avoid "No Access" users showing in the notified list in editorial comments
Adds `.post_following_list-no_access` to the "No Access" warning spans (in two places), then uses that during "Notified list" generation to exclude people without access from the list (which already happens during email sending, this just cleans up the display so it matches the actual outcome).
My intention is to add similar tests for current_user and no_email users.
- `notifications.php` - add …

For #483 - Updates notifications js/php to only show users who will be notified

---

modules/notifications/lib/notifications.js

( @rinatkhaziev I know you said you were trying to wrap up for today, but it turned out pretty easy to make this change and I think it goes well with the others. The colors are from the WP colors codepen)
Before: It would flash green as long as the AJAX came back
Now: It flashes red when you've ticked a user with a warning, otherwise green
- sets a `warning_background = true` flag during `toggle_warning_badges()`
- uses that flag in the AJAX response to choose between green and red background
- re-organizes the code a bit to run `toggle_warning_badges()` before the animation and fix an indentation issue

notifications.js - Update background color that flashes when ticking/unticking users

---

.travis.yml

Also bump up testing using WP 5.1+

Remove TravisCI tests for anything below PHP 5.6

---

modules/custom-status/custom-status.php

This PR resolves #513.  Since the check (https://github.com/WordPress/WordPress/blob/cf3fa9f7c8038447303eea1fbd3636c5fece28cd/wp-admin/includes/post.php#L1808) in `wp_create_post_autosave()` fails because an autosave is not present for unpublished posts saved with custom statuses, `preview_nonce` gets added onto the preview link.  This also piggybacks off the logic in `wp_create_autosave()` to check if this is a personal preview: https://github.com/WordPress/WordPress/blob/cf3fa9f7c8038447303eea1fbd3636c5fece28cd/wp-admin/includes/post.php#L1791

Filter post_preview_link for a viewable preview link

---

modules/editorial-comments/lib/editorial-comments.js

Was getting a missing function error for the $, and it was creating a conflict with another plugin. As I understand it, when using jQuery in WordPress, best practice is to always use the jQuery function instead of the $. Updated this file (the source of the error) and everything is peachy. It would be great to have this change rolled into the plug-in, so that I don’t have to keep making it after each update.
Also, I hope I’m going about this the correct way. I got followed the instructions from the plugin website (I think). I’ve never use git for collaboration, so if I did this wrong, please feel free to correct me, it won’t hurt my feelings at all.

Replace “$” with “jQuery”.

---

.travis.yml

- Add MySQL as a service inside Travis
- Use the custom installed version of PHPUnit if there is one.
Travis should have been calling the globally installed version according to [here](https://docs.travis-ci.com/user/languages/php/#default-build-script), but for some reason was not.
The custom PHPUnit install logic can probably be dropped once support for PHP 7.1/7.2 is no longer required.

Fix failing TravisCI tests

---

edit-flow.php

From the compat file. Having the headers in both the underscore and hyphen version of the files results in two copies of "Edit Flow" showing up in the Plugin list.
Related #512

Remove extra plugin headers

---

.travis.yml

Updates the CI build versions to use current and previous version of PHP 7.x
Note: `nightly` cannot currently work due to a conflict between PHPUnit dependencies and the WordPress version requirements.  Nightly (PHP 8.0.0-dev) requires PHPUnit 8+ but the WordPress test suite only works with PHPUnit 5.7 or older.

Update PHP 7 version in TravicCI build Matrix

---

edit_flow.php
modules/settings/settings.php

```
PHP Warning: count(): Parameter must be an array or an object that implements Countable
```
Switch to a another instance var that tracks the module count rather than trying to force the `modules` object into an array and back.
Fixes #498 
1. Make sure you're using PHP 7.2 or newer and `WP_DEBUG` is set.
1. Goto `/wp-admin/admin.php?page=ef-settings`
1. Should see the warning.
1. Apply patch.
1. Refresh page and verify that error is gone and page renders correctly.

Fix PHP count() warning

---

modules/user-groups/user-groups.php

Resolves #489.
Resolves #255.
This pull request adds a check for `is_admin` before checking if the `get_current_screen()` function exists.
The function `get_current_screen()` "[is defined on most admin pages, but not all.](https://codex.wordpress.org/Function_Reference/get_current_screen#Usage_Restrictions)". This suggests that the function should be checked before being called, particulalry if not the code is used on admin and non-admin pages alike.
Specifically, this code runs on the `user_profile_update_errors` action which is triggered by front-end user profile pages.

Wrap network check in function_exists() block

---

common/php/class-module.php
common/php/trait-block-editor-compatible.php
modules/custom-status/compat/block-editor.php
modules/custom-status/custom-status.php
readme.txt

Otherwise we end up triggering the compat hooks which can lead to breakages because of unexpected contexts (e.g. custom status javascript being loaded without necessary data).
Fixes #522
1. Disable block editor (by installing and activating "Classic Editor" plugin)
1. Disable "Custom Statuses" module.
1. Editing a post will throw the error.
1. Apply patch.
1. Error should be gone.
Also, verify that the Block Editor is not impacted in any way:
1. Enable Custom Status and make sure editing works and custom status can be set and changed.
1. Disable Custom Status and make sure editing still works.

Check module is enabled before compat init

---

readme.txt

- WordPress 5.1 (current - 1)
- PHP 5.6 (matches WordPress' min)
And tested up to WordPress 5.3.

Bump min versions

---

modules/notifications/notifications.php

Anytime a post is saved, the current user is subscribed to the notifications. This includes when trying to remove themselves from the notification list resulting in it being impossible to unsubscribe from a post..  
This PR skips auto-subscribing the current user whenever the notifications settings are updated.All other auto-subscribe functionality is retained. The current user can still subscribe to the post and if they explicitly save it, they will be resubscribed. 
Related to #519 #520 
1. Edit to a post not owned by you
2. Unsubscribe from notifications.
3. Refresh the page and note that you were not unsubscribed
4. Apply patch
5. Unsubscribe from the post
6. Refresh the page, and note that you are now unsubscribed
7. Save the post
8. Refresh the page and confirm you are resubscribed

Don't auto-subscribe the current user when notification settings are changed

---

.gitignore
.svnignore
PUBLISHING.md
bin/prepare-svn-release.sh

Add docs around publishing a new release to WP.org and update the release script to skip development files.

Publishing Instructions

---

.travis.yml

Currently broken and tends to be unstable and therefore not really useful to test against.

Don't test PHP nightly

---

blocks/dist/custom-status.build.js
blocks/src/custom-status/block.js

Remove reference to the getStatusLabel function which is no longer used.
Fixes #553 
See #555
Copied from #555:
To validate successful schedule
Create a post
Schedule it for the future
Hit the "Schedule" button
Confirm the post is scheduled, no errors in console
To validate successful trash
Create a post
Publish it
Click Move To Trash
Confirm the post is moved to trash, no errors in console
To validate status being set
Create a post
Change it's status to "Assigned"
Click "Save as Assigned"
Confirm that after saving, "Save as Assigned" still appears
Verify the same functionality works in Classic Editor as well.

Prevent js errors when scheduling / trashing post

---

modules/custom-status/custom-status.php
tests/test-edit-flow-custom-status.php

Fix for #551 
`display_post_states` has two arguments, one of them `$post` (since WP 3.6). Use the argument instead of the global `$post`

Fix WP Menu post title notice

---

.gitignore
.travis.yml
bin/phpcs-diff.sh
composer.json
composer.lock
phpcs.xml.dist

This change executes PHPCS (`WordPress-VIP-Go`) on Travis. It should execute only on changed lines of code. It will output the line and rule violation that occurred in the console of the Travis build. You can also run it from your local machine after committing a change (could run on staged diff as well, with changes).
Eventually, we may want to:
- Introduce a larger coverage scope (run PHPCS over a whole file, not just the changes)
- Make this part of a pre-commit hopok
But in the meantime, it should introduce a lightweight sanity check for new changes to ensure we're not introducing any new violations without acting as a blocker

Adding phpcs as part of Travis build process

---

.travis.yml

- WP 5.3 was released recently and we only care about n-1 major releases.
- PHP 7.4 was released recently.
Make sure Travis is testing the right matrix envs and looks happy.

Travis: drop WP 5.1 and add PHP 7.4

---

bin/phpcs-diff.sh

On Travis, PHPCS is being run on all files (PHP, JS, etc). This will limit PHPCS to be run only on *.php files.

Run PHPCS on php files only

---

.travis.yml
bin/phpcs-diff.sh
phpcs.xml.dist

Quick update to the Travis yaml to run extras (PHPCS diff, lint and e2e tests) only on certain conditions (when `RUN_EXTRAS` environment variable is set).
Also, actually limit PHPCS to run over only PHP files (was previously just limiting the diff output).
Making sure to exclude the new `wordpress` [directory that gets included](https://github.com/Automattic/Edit-Flow/pull/573/files#diff-6758ef1f416bd888bd1a5cad8f97cc2bR12) by e2e tests

Update Travis test extras

---

bin/phpcs-diff.sh

The filtering of the diff `-- '*.php'` is resulting in an empty file. With the usage of `--extensions=php` [in PHPCS should](https://github.com/Automattic/Edit-Flow/compare/fix/phpcs-diff?expand=1#diff-219bf2a45ce55a542f916415298efd7eR11) we should be able to avoid having to figure out how to filter on the diff

Small change to phpcs-diff

---

modules/dashboard/widgets/dashboard-notepad.php

Fixes https://github.com/Automattic/Edit-Flow/issues/471
The else clause was actually necessary for the first time a note was created. It was a bit confusing though, so I've cleaned up the logic to make a single path of execution. `wp_insert_post()` will handle updating the post if the ID is passed.
Checkout the PR and update the dashboard note. Can also delete the post from the database manually and then ensure you're still able to create a note.

Clean up dashboard-note logic

---

modules/custom-status/custom-status.php
modules/custom-status/lib/custom-status.css
tests/test-edit-flow-custom-status.php

Closes https://github.com/Automattic/Edit-Flow/issues/395
Custom post statuses has enough hacks as-is, let's adhere to core APIs and standards when we can :)
Instead of adding an extra column to the post list that takes up valuable space, let's follow core's UI and display custom statuses just like other statuses are shown in WP.
For some context, here is what is done in WP core: https://github.com/WordPress/WordPress/blob/dd4d98a368ca1d617adfaaef9b2937c60464ac4a/wp-admin/includes/template.php#L2100-L2170. Of note, I followed the same rules by letting core continue to handle some statuses specially, and by not showing the status when a specific post status is filtered.
It will also smartly handle cases where EF has changed a core statuses name (like pending). Thanks to the use of array …

Display custom statuses in post states

---

modules/editorial-comments/editorial-comments.php

This function was created as a placeholder while waiting for https://core.trac.wordpress.org/ticket/10668
It's been a decade now, and core's `get_comments()` does what we need now 🙂. I did search around some though and can confirm that `ef_get_comments_plus()` is actually used outside EF in a few scenarios. So I've left it there and added a deprecation notice (version TBD).
Also removed some commented-out code. It's probably been a decade for these poor souls as well, and we can rely on version control if they were ever missed.

Deprecate ef_get_comments_plus()

---

common/php/class-module.php

This attaches the `var` definition to the script itself, so it will only output when the script tag is actually printed, rather than just enqueued.
If you only call `wp_enqueue_scripts`, this just registers & enqueues the scripts, but doesn't necessarily print them. This was causing a conflict when the [PWA](https://github.com/xwp/pwa-wp) plugin is active. [It calls `admin_enqueue_scripts` to set up scripts for caching,](https://github.com/xwp/pwa-wp/blob/90767479119a06c544c659778c46c7c6a6768baa/wp-includes/class-wp-service-workers.php#L124) but it never outputs the script. See https://github.com/WordPress/wordcamp.org/pull/328 for my (hopefully temporary 😁) workaround.
1. Check out PR.
2. View source on a page, see that the variable is defined immediately before the script tag now
3. …

Add `ef_week_first_day` as script data to prevent echoing script tags

---

modules/editorial-metadata/editorial-metadata.php

Move 'Customize' link in Metadata metabox to inside metabox

---

modules/editorial-metadata/editorial-metadata.php

Spotted this just after I hit the merge button on #590 
The `esc_url` was dropped, adding it back in

Add back escape

---

modules/editorial-comments/editorial-comments.php
tests/e2e/specs/editorial-comments.test.js

A fix for #588
For some reason, when `post` is a dependency of the Editorial Comment js, the custom fields get duplicated. Not sure why we have `post` as a dependency in the first place since all we use is `wpAjax`. 
Also, created a quick e2e test to validate the creation of an editorial comment

Prevent multiple custom fields from being created

---

common/js/ef_date.js
modules/story-budget/story-budget.php
tests/test-edit-flow-story-budget.php

The story budget date picker has the same issue fixed in #546. Fix the i18n issues to better support localization of the story budget.

Support i18n in story budget date picker

---

modules/custom-status/custom-status.php

Bug description:
The author of a post can preview changes to their own published posts,
but other users see the content of the published post when previewing.
This is due to checking for the autosaves of `$query_args->post_author`
instead of the autosaves of `get_current_user_id()`.
Steps to reproduce:
1. Log in as user A
2. Create a new post, press "Publish"
3. Log in as user B
4. Visit the edit page for the post that was just created
5. Add to the post's content (without pressing "Update")
6. Click "Preview"
Expected behaviour:
The content added by user B appears in the preview.
Actual behaviour:
The content added by user B doesn't appear in the preview of the post.

Fix bug preventing previewing posts authored by other users

---

modules/calendar/calendar.php
package-lock.json

The "Unpublish" status for calendar was dropped with the recent Gutenberg changes. Reintroduce this status

Add back unpublish status, small css tweak for statuses

---

modules/settings/lib/settings.js
modules/settings/settings.php

Fix #631 
---
This PR is pretty simple. It's simply to use `slug` of each module and append it to the current name/id. 
1. Apply this PR.
2. Visit wp-admin/admin.php?page=ef-settings
3. No longer see `Found 8 elements with non-unique id #change-module-nonce` error in your browser console.
4. See this page's HTML source, search `change-module-nonce`, there will be 8 results with a different suffix.

Fix: Give each attribute in Edit Flow settings page a different id

---

.github/workflows/php-tests.yml
bin/phpcs-diff.sh
composer.json

Partly fix #638
Close #647
- Update "coverage-checker" so that it can support PHP 8.0.
- Stop running PHPCS for PHP 8.0 as WPCS is not ready as mentioned here https://github.com/Automattic/Edit-Flow/issues/638#issuecomment-825511819.
- Update bin/phpcs-diff.sh then (1) it will not fetch all branches (we just need `master` branch), and (2) it will show errors when diff lines do not conform with PHPCS. Currently, it does not exit with any error. 
- Remove tests for PHP 8.1 - [see here](https://github.com/Parsely/wp-parsely/blob/152c1dd9b288f9ae66e2c521171194df5f7170b8/.github/workflows/integration-tests.yml#L33).
Mainly check the relevant GitHub Actions for PHP Tests here. 
Note: for PHP 8.0 test failure, it will be addressed in another PR as the solution is here …

PHP 8.0 and PHPCS: partly fix compatibility with composer packages

---

modules/story-budget/story-budget.php

Fix #639 
Details here https://github.com/Automattic/Edit-Flow/issues/639#issuecomment-836384914
This PR should be merged after this PR https://github.com/Automattic/Edit-Flow/pull/643 - actually, this PR is rebased on PR 643. 
1. Check out PR.
1. Set up WP test site `bash bin/install-wp-tests.sh wordpress_test root root`.
2. Run PHPUnit tests in PHP 8.0.x `composer integration`.
3. Confirm that all tests pass.

Fix test_story_budget_set_number_days_filter_invalid in PHP 8.0

---

modules/custom-status/custom-status.php

Fix #633 
This is to address the issue as mentioned in issue #633. It was introduced from this PR https://github.com/Automattic/Edit-Flow/pull/575 that fixes a relevant issue with post slug in Gutenberg https://github.com/Automattic/Edit-Flow/issues/523. 
The issue is happening around these lines:
http://github.com/Automattic/Edit-Flow/blob/124c3cde900c22abe15c04b0b2bd11e306b2aef4/modules/custom-status/custom-status.php#L1390-L1394
In this PR, I am just running [sanitize_title](https://developer.wordpress.org/reference/functions/sanitize_title/) to fix this issue. 
It's not an issue with Gutenberg as Gutenberg itself tries to convert the slug in the front-end before sending it to the back-end: 
- See the screenshot below
- Relevant code: …

Fix: updating post slugs in Quick Edit and Classic Editor

---

composer.json

Enables `composer cs` for easily running PHPCS over project

add 'cs' script to composer for easy running of phpcs

---

common/js/jquery-ui-timepicker-addon.js
common/js/jquery.listfilterizer.js
common/js/jquery.quicksearch.js
common/js/screen-options.js
modules/calendar/lib/calendar.js
modules/custom-status/lib/custom-status-configure.js
modules/custom-status/lib/custom-status.js
modules/editorial-comments/lib/editorial-comments.js
modules/editorial-metadata/lib/editorial-metadata-configure.js
modules/settings/lib/settings.js
modules/story-budget/lib/story-budget.js
modules/user-groups/lib/user-groups-configure.js

Fix #632 
---
This PR has done these changes to fix all warnings: 
| Old      | New | Ref | 
| ----------- | ----------- | ----------- |
| jQuery.expr[':']      | jQuery.expr.pseudos       |
| .click(fn)   | .on("click", fn)       | [Reference](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated)
| .click()   | .trigger("click")      | [Reference](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnclick-event-shorthand-is-deprecated)
| .hover(fn1, fn2)   | .on("mouseenter", fn1).on("mouseleave", fn2)  | [Reference](https://github.com/jquery/jquery-migrate/blob/main/warnings.md#jqmigrate-jqueryfnhover-is-deprecated) | 
| removeAttr('selected'); | prop( 'selected', false ); | …

Fix jQuery warnings as WordPress upgraded it from 1.12.4-wp to 3.5.1

---

tests/e2e/utils/index.js

Fix #652 
The root cause is described here https://github.com/Automattic/Edit-Flow/issues/652#issuecomment-857577431
To fix this issue, I am changing the way selecting a future date for schedulePost: 
- Calculate the date in 2 weeks since today. 
- Use DOM selector and update the respective values for day, month, year. 
- I researched how Gutenberg approaches this issue and at the moment, there is no support for creating schedule posts in package `e2e-test-utils`. I pulled Gutenberg and searched on this specific folder `packages/e2e-test-utils/src`, which hosts this package.
- Instead, here is how a similar issue (updating date and time of a post) is handled in Gutenberg. That's basically the same method I am using here https://github.com/WordPress/gutenberg/pull/27558/files#diff-3836a6db8 …

Update the way selecting a future date for schedulePost 

---

modules/custom-status/lib/custom-status.js

Fix https://github.com/Automattic/Edit-Flow/issues/662
---
This is pretty straightforward as all research has been done in https://github.com/Automattic/Edit-Flow/issues/662
1. Apply this PR.
2. Apply the diff in the **Note** section for `edit_flow.php` to avoid caching issue for JS files https://github.com/Automattic/Edit-Flow/pull/649
3. Visit wp-admin > Posts
✅ if we can use `Quick Edit` and change custom status without any issue.

Remove redundant jQuery selector #the-list a.editinline

---

modules/story-budget/lib/story-budget.js

Fix https://github.com/Automattic/Edit-Flow/issues/663
---
All research has been done in https://github.com/Automattic/Edit-Flow/issues/663
1. Apply this PR.
2. Apply the diff in the **Note** section for `edit_flow.php` to avoid caching issue for JS files https://github.com/Automattic/Edit-Flow/pull/649
3. Visit wp-admin > Dashboard > Story Budget. 
✅ if we can change `Screen Options`, click actions for posts, etc without any issue.

Remove redundant jQuery selector #toggle_details

---

common/php/screen-options.php

Fixes https://github.com/Automattic/Edit-Flow/issues/656
Currently there's a PHP Notice happening when you save screen option changes:
`[07-Jun-2021 18:36:16 UTC] PHP Notice:  Only variables should be passed by reference in wp-content/plugins/Edit-Flow/common/php/screen-options.php on line 169`
1. Go to `wp-admin/index.php?page=story-budget`
2. Click on Screen Options at the top
3. Change the number of columns
4. Refresh the page to make sure the setting was saved

Fixes non-variable being passed by reference

---

common/php/class-module.php

Fixes deprecation notice `Deprecated: WP_User_Query was called with an argument that is deprecated since version 5.9.0! who is deprecated. Use capability instead.`
Uses `publish_posts` cap since that's the one granted to authors and above.
Go to wp-admin > Posts > Add New Post and see if it triggers in PHP logs/QM

Fix WP 5.9 deprecation notice with `who` in WP_User_Query

---

common/php/class-module.php
edit_flow.php
modules/calendar/calendar.php
modules/story-budget/story-budget.php
tests/test-edit-flow-custom-status-ajax.php
tests/test-edit-flow-custom-status.php

Alternative to #699 
Check QM and php logs to ensure no more PHP 8.2 dynamic property deprecation notices are being set.

Add PHP 8.2 fixes
